runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: web_profile/profile.html
  upload: web_profile/profile.html

- url: /(.*)
  static_files: web_profile/\1
  upload: web_profile/(.*)
